# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 470ca648b11baa3aaaba8f84bb69f30774210ae0eeeff3b1527b6b10958b42ebf387934c052dba2d199dd8ccd7611b00ec1aff405d48893f14138b3ecc60abf7

test:
  secret_key_base: 2aa96e764058297bdfee981b913d0fa5e3b79dd13486b9dc7d681ba9899fc3fffc7b2a69b455b2ba73bff34c75a6eff7e0860c863c9a6a79dfbfb4bb3c6b3ae1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
